# Generated by Django 2.2.5 on 2020-11-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201106_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirm',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_secret_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
