# Generated by Django 2.2.5 on 2020-11-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModelManager',
        ),
    ]
