# Generated by Django 2.2.5 on 2020-11-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20201103_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleanlines',
            new_name='cleanliness',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='communitcation',
            new_name='communication',
        ),
    ]
